//
// Created by MERHAB NOUREDDINE on 04/10/2024.
// Copyright (c) 2024 MERHAB NOUREDDINE. All rights reserved.
//

#pragma once
#include <QString>
#include <QApplication>

inline QApplication * app;

inline QString cssSysNet ="QWidget\n"
                          "{\n"
                          "\tbackground-color: #1a1a1a;\n"
                          "\tcolor: #000000;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "/*-----QLabel-----*/\n"
                          "QLabel\n"
                          "{\n"
                          "\tbackground-color: transparent;\n"
                          "\tcolor: #c2c7d5;\n"
                          "\tfont-size: 13px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "/*-----QPushButton-----*/\n"
                          "QPushButton\n"
                          "{\n"
                          "\tbackground-color: #ff3333;\n"
                          "\tcolor: #fff;\n"
                          "\tfont-size: 11px;\n"
                          "\tfont-weight: bold;\n"
                          "\tborder: none;\n"
                          "\tborder-radius: 25px;\n"
                          "\tpadding: 5px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QPushButton::disabled\n"
                          "{\n"
                          "\tbackground-color: #5c5c5c;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QPushButton::pressed\n"
                          "{\n"
                          "\tbackground-color: #ff4747;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "/*-----QCheckBox-----*/\n"
                          "QCheckBox\n"
                          "{\n"
                          "\tbackground-color: transparent;\n"
                          "\tcolor: #fff;\n"
                          "\tfont-size: 10px;\n"
                          "\tfont-weight: bold;\n"
                          "\tborder: none;\n"
                          "\tborder-radius: 5px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "/*-----QCheckBox-----*/\n"
                          "QCheckBox::indicator\n"
                          "{\n"
                          "    color: #b1b1b1;\n"
                          "    background-color: #323232;\n"
                          "    border: 1px solid darkgray;\n"
                          "    width: 12px;\n"
                          "    height: 12px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QCheckBox::indicator:checked\n"
                          "{\n"
                          "    image:url(\"./ressources/check.png\");\n"
                          "\tbackground-color: #ff3333;\n"
                          "    border: 1px solid #ff3333;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QCheckBox::indicator:unchecked:hover\n"
                          "{\n"
                          "    border: 1px solid #ff3333;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QCheckBox::disabled\n"
                          "{\n"
                          "\tcolor: #656565;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QCheckBox::indicator:disabled\n"
                          "{\n"
                          "\tbackground-color: #656565;\n"
                          "\tcolor: #656565;\n"
                          "    border: 1px solid #656565;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "/*-----QLineEdit-----*/\n"
                          "QLineEdit\n"
                          "{\n"
                          "\tbackground-color: #c2c7d5;\n"
                          "\tcolor: #000;\n"
                          "\tfont-weight: bold;\n"
                          "\tborder: none;\n"
                          "\tborder-radius: 2px;\n"
                          "\tpadding: 3px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "/*-----QListView-----*/\n"
                          "QListView\n"
                          "{\n"
                          "\tbackground-color: #333333;\n"
                          "\tcolor: #fff;\n"
                          "\tfont-size: 12px;\n"
                          "\tfont-weight: bold;\n"
                          "\tborder: 1px solid #191919;\n"
                          "\tshow-decoration-selected: 0;\n"
                          "\tpadding-left: -13px;\n"
                          "\tpadding-right: -13px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QListView::item\n"
                          "{\n"
                          "\tcolor: #31cecb;\n"
                          "\tbackground-color: #454e5e;\n"
                          "\tborder: none;\n"
                          "\tpadding: 5px;\n"
                          "\tborder-radius: 0px;\n"
                          "\tpadding-left : 10px;\n"
                          "\theight: 42px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "QListView::item:selected\n"
                          "{\n"
                          "\tcolor: #000;\n"
                          "\tbackground-color: #ff3333;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QListView::item:!selected\n"
                          "{\n"
                          "\tcolor:white;\n"
                          "\tbackground-color: transparent;\n"
                          "\tborder: none;\n"
                          "\tpadding-left : 10px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QListView::item:!selected:hover\n"
                          "{\n"
                          "\tcolor: #000;\n"
                          "\tbackground-color: #bcbdbb;\n"
                          "\tborder: none;\n"
                          "\tpadding-left : 10px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "/*-----QTreeView-----*/\n"
                          "QTreeView \n"
                          "{\n"
                          "\tbackground-color: #252525;\n"
                          "\tshow-decoration-selected: 0;\n"
                          "\tcolor: #c2c8d7;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QTreeView::item \n"
                          "{\n"
                          "\tborder-top-color: transparent;\n"
                          "\tborder-bottom-color: transparent;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QTreeView::item:hover \n"
                          "{\n"
                          "\tbackground-color: #bcbdbb;\n"
                          "\tcolor: #000;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QTreeView::item:selected \n"
                          "{\n"
                          "\tbackground-color: #ff3333;\n"
                          "\tcolor: #000;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QTreeView::item:selected:active\n"
                          "{\n"
                          "\tbackground-color: #ff3333;\n"
                          "\tcolor: #000;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QTreeView::branch:has-children:!has-siblings:closed,\n"
                          "QTreeView::branch:closed:has-children:has-siblings \n"
                          "{\n"
                          "\timage: url(://tree-closed.png);\n"
                          "\n"
                          "}\n"
                          "\n"
                          "QTreeView::branch:open:has-children:!has-siblings,\n"
                          "QTreeView::branch:open:has-children:has-siblings  \n"
                          "{\n"
                          "\timage: url(://tree-open.png);\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "/*-----QTableView & QTableWidget-----*/\n"
                          "QTableView\n"
                          "{\n"
                          "    background-color: #252525;\n"
                          "\tborder: 1px solid gray;\n"
                          "    color: #f0f0f0;\n"
                          "    gridline-color: gray;\n"
                          "    outline : 0;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QTableView::disabled\n"
                          "{\n"
                          "    background-color: #242526;\n"
                          "    border: 1px solid #32414B;\n"
                          "    color: #656565;\n"
                          "    gridline-color: #656565;\n"
                          "    outline : 0;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QTableView::item:hover \n"
                          "{\n"
                          "    background-color: #bcbdbb;\n"
                          "    color: #000;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QTableView::item:selected \n"
                          "{\n"
                          "\tbackground-color: #ff3333;\n"
                          "    color: #000;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QTableView::item:selected:disabled\n"
                          "{\n"
                          "    background-color: #1a1b1c;\n"
                          "    border: 2px solid #525251;\n"
                          "    color: #656565;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QTableCornerButton::section\n"
                          "{\n"
                          "\tbackground-color: #343a49;\n"
                          "    color: #fff;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QHeaderView::section\n"
                          "{\n"
                          "\tcolor: #fff;\n"
                          "\tborder-top: 0px;\n"
                          "\tborder-bottom: 1px solid gray;\n"
                          "\tborder-right: 1px solid gray;\n"
                          "\tbackground-color: #343a49;\n"
                          "    margin-top:1px;\n"
                          "\tmargin-bottom:1px;\n"
                          "\tpadding: 5px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QHeaderView::section:disabled\n"
                          "{\n"
                          "    background-color: #525251;\n"
                          "    color: #656565;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QHeaderView::section:checked\n"
                          "{\n"
                          "    color: #000;\n"
                          "    background-color: #ff3333;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QHeaderView::section:checked:disabled\n"
                          "{\n"
                          "    color: #656565;\n"
                          "    background-color: #525251;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QHeaderView::section::vertical::first,\n"
                          "QHeaderView::section::vertical::only-one\n"
                          "{\n"
                          "    border-top: 1px solid #353635;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QHeaderView::section::vertical\n"
                          "{\n"
                          "    border-top: 1px solid #353635;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QHeaderView::section::horizontal::first,\n"
                          "QHeaderView::section::horizontal::only-one\n"
                          "{\n"
                          "    border-left: 1px solid #353635;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QHeaderView::section::horizontal\n"
                          "{\n"
                          "    border-left: 1px solid #353635;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "/*-----QScrollBar-----*/\n"
                          "QScrollBar:horizontal \n"
                          "{\n"
                          "    background-color: transparent;\n"
                          "    height: 8px;\n"
                          "    margin: 0px;\n"
                          "    padding: 0px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QScrollBar::handle:horizontal \n"
                          "{\n"
                          "    border: none;\n"
                          "\tmin-width: 100px;\n"
                          "    background-color: #9b9b9b;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QScrollBar::add-line:horizontal, \n"
                          "QScrollBar::sub-line:horizontal,\n"
                          "QScrollBar::add-page:horizontal, \n"
                          "QScrollBar::sub-page:horizontal \n"
                          "{\n"
                          "    width: 0px;\n"
                          "    background-color: transparent;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QScrollBar:vertical \n"
                          "{\n"
                          "    background-color: transparent;\n"
                          "    width: 8px;\n"
                          "    margin: 0;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QScrollBar::handle:vertical \n"
                          "{\n"
                          "    border: none;\n"
                          "\tmin-height: 100px;\n"
                          "    background-color: #9b9b9b;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QScrollBar::add-line:vertical, \n"
                          "QScrollBar::sub-line:vertical,\n"
                          "QScrollBar::add-page:vertical, \n"
                          "QScrollBar::sub-page:vertical \n"
                          "{\n"
                          "    height: 0px;\n"
                          "    background-color: transparent;\n"
                          "\n"
                          "}";

inline QString cssGlobal ="/*-----QWidget-----*/\n"
                            "QWidget\n"
                            "{\n"
                            "\tbackground-color: #121212;\n"
                            "\tcolor: #ffffff;\n"
                            "\tborder-color: #051a39;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "/*-----QLabel-----*/\n"
                            "QLabel\n"
                            "{\n"
                            "\tbackground-color: transparent;\n"
                            "\tcolor: #ffffff;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QLabel::disabled\n"
                            "{\n"
                            "\tbackground-color: transparent;\n"
                            "\tcolor: #656565;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "/*-----QMenuBar-----*/\n"
                            "QMenuBar\n"
                            "{\n"
                            "\tbackground-color: #0a0a0a;\n"
                            "\tcolor: #ffffff;\n"
                            "\tborder-color: #051a39;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QMenuBar::disabled\n"
                            "{\n"
                            "\tbackground-color: #404040;\n"
                            "\tcolor: #656565;\n"
                            "\tborder-color: #051a39;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QMenuBar::item\n"
                            "{\n"
                            "    background-color: transparent;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QMenuBar::item:selected\n"
                            "{\n"
                            "    background-color: #607cff;\n"
                            "    border: 1px solid #41cd52;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QMenuBar::item:pressed\n"
                            "{\n"
                            "    background-color: #4969ff;\n"
                            "    border: 1px solid #000;\n"
                            "    margin-bottom: -1px;\n"
                            "    padding-bottom: 1px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "/*-----QMenu-----*/\n"
                            "QMenu\n"
                            "{\n"
                            "    background-color: #121212;\n"
                            "    border: 1px solid;\n"
                            "    color: #ffffff;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QMenu::separator\n"
                            "{\n"
                            "    height: 1px;\n"
                            "    background-color: #6d8eff;\n"
                            "    color: #ffffff;\n"
                            "    padding-left: 4px;\n"
                            "    margin-left: 10px;\n"
                            "    margin-right: 5px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QMenu::item\n"
                            "{\n"
                            "    min-width : 150px;\n"
                            "    padding: 3px 20px 3px 20px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QMenu::item:selected\n"
                            "{\n"
                            "    background-color: #4969ff;\n"
                            "    color: #ffffff;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QMenu::item:disabled\n"
                            "{\n"
                            "    color: #262626;\n"
                            "}\n"
                            "\n"
                            "\n"
                            "/*-----QToolTip-----*/\n"
                            "QToolTip\n"
                            "{\n"
                            "\tborder : 1px solid #000000;\n"
                            "\tbackground-color: #26264f;\n"
                            "\tcolor: #ffffff;\n"
                            "\tborder-color: #051a39;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "\n"
                            "/*-----QPushButton-----*/\n"
                            "QPushButton\n"
                            "{\n"
                            "\tbackground-color: #607cff;\n"
                            "\tcolor: #ffffff;\n"
                            "\tborder-style: solid;\n"
                            "\tborder-width: 1px;\n"
                            "\tborder-radius: 3px;\n"
                            "\tborder-color: #051a39;\n"
                            "\tpadding: 5px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QPushButton::disabled\n"
                            "{\n"
                            "\tbackground-color: #404040;\n"
                            "\tcolor: #656565;\n"
                            "\tborder-color: #051a39;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QPushButton::hover\n"
                            "{\n"
                            "\tbackground-color: #8399ff;\n"
                            "\tcolor: #ffffff;\n"
                            "\tborder-style: solid;\n"
                            "\tborder-width: 1px;\n"
                            "\tborder-radius: 3px;\n"
                            "\tborder-color: #051a39;\n"
                            "\tpadding: 5px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QPushButton::pressed\n"
                            "{\n"
                            "\tbackground-color: #4969ff;\n"
                            "\tcolor: #ffffff;\n"
                            "\tborder-style: solid;\n"
                            "\tborder-width: 1px;\n"
                            "\tborder-radius: 3px;\n"
                            "\tborder-color: #051a39;\n"
                            "\tpadding: 5px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "/*-----QToolButton-----*/\n"
                            "QToolButton\n"
                            "{\n"
                            "\tbackground-color: #607cff;\n"
                            "\tcolor: #ffffff;\n"
                            "\tborder-width: 1px;\n"
                            "\tborder-radius: 3px;\n"
                            "\tborder-color: #051a39;\n"
                            "\tpadding: 3px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QToolButton::disabled\n"
                            "{\n"
                            "\tbackground-color: #404040;\n"
                            "\tcolor: #656565;\n"
                            "\tborder-color: #051a39;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QToolButton::hover\n"
                            "{\n"
                            "\tbackground-color: #8399ff;\n"
                            "\tcolor: #ffffff;\n"
                            "\tborder-width: 1px;\n"
                            "\tborder-radius: 3px;\n"
                            "\tborder-color: #051a39;\n"
                            "\tpadding: 3px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QToolButton::pressed\n"
                            "{\n"
                            "\tbackground-color: #4969ff;\n"
                            "\tcolor: #ffffff;\n"
                            "\tborder-width: 1px;\n"
                            "\tborder-radius: 3px;\n"
                            "\tborder-color: #051a39;\n"
                            "\tpadding: 3px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "/*-----QComboBox-----*/\n"
                            "QComboBox\n"
                            "{\n"
                            "    background-color: #607cff;\n"
                            "    border: 1px solid;\n"
                            "    border-radius: 3px;\n"
                            "    padding-left: 6px;\n"
                            "    color: #ffffff;\n"
                            "    height: 20px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QComboBox::disabled\n"
                            "{\n"
                            "\tbackground-color: #404040;\n"
                            "\tcolor: #656565;\n"
                            "\tborder-color: #051a39;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QComboBox:hover\n"
                            "{\n"
                            "    background-color: #8399ff;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QComboBox:on\n"
                            "{\n"
                            "    background-color: #4969ff;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QComboBox QAbstractItemView\n"
                            "{\n"
                            "    background-color: #383838;\n"
                            "    color: #ffffff;\n"
                            "    border: 1px solid black;\n"
                            "    selection-background-color: #4969ff;\n"
                            "    selection-color: #ffffff;\n"
                            "    outline: 0;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QComboBox::drop-down\n"
                            "{\n"
                            "    subcontrol-origin: padding;\n"
                            "    subcontrol-position: top right;\n"
                            "    width: 15px;\n"
                            "    border-left-width: 0px;\n"
                            "    border-left-color: darkgray;\n"
                            "    border-left-style: solid; \n"
                            "    border-top-right-radius: 3px; \n"
                            "    border-bottom-right-radius: 3px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QComboBox::down-arrow\n"
                            "{\n"
                            "    image: url(://arrow-down.png);\n"
                            "    width: 8px;\n"
                            "    height: 8px;\n"
                            "}\n"
                            "\n"
                            "\n"
                            "/*-----QSpinBox & QDoubleSpinBox & QDateTimeEdit-----*/\n"
                            "QSpinBox, \n"
                            "QDoubleSpinBox,\n"
                            "QDateTimeEdit\n"
                            "{\n"
                            "\tbackground-color: #525251;\n"
                            "\tcolor: #ffffff;\n"
                            "\tborder: 1px solid #051a39;\n"
                            "\tborder-radius: 3px;\n"
                            "\tpadding : 2px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSpinBox::disabled, \n"
                            "QDoubleSpinBox::disabled,\n"
                            "QDateTimeEdit::disabled\n"
                            "{\n"
                            "\tbackground-color: #404040;\n"
                            "\tcolor: #656565;\n"
                            "\tborder-color: #051a39;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSpinBox:hover, \n"
                            "QDoubleSpinBox::hover,\n"
                            "QDateTimeEdit::hover\n"
                            "{\n"
                            "    background-color: #626262;\n"
                            "    border: 1px solid #607cff;\n"
                            "    color:  #fff;\n"
                            "    padding: 2px\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSpinBox::up-button, QSpinBox::down-button,\n"
                            "QDoubleSpinBox::up-button, QDoubleSpinBox::down-button,\n"
                            "QDateTimeEdit::up-button, QDateTimeEdit::down-button\n"
                            "{\n"
                            "    background-color: #607cff;\n"
                            "\tborder-radius: 2px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSpinBox::disabled, \n"
                            "QDoubleSpinBox::disabled,\n"
                            "QDateTimeEdit::disabled\n"
                            "{\n"
                            "\tbackground-color: #404040;\n"
                            "\tcolor: #656565;\n"
                            "\tborder-color: #051a39;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSpinBox::up-button:hover, QSpinBox::down-button:hover,\n"
                            "QDoubleSpinBox::up-button:hover, QDoubleSpinBox::down-button:hover,\n"
                            "QDateTimeEdit::up-button:hover, QDateTimeEdit::down-button:hover\n"
                            "{\n"
                            "    background-color: #8399ff;\n"
                            "    border: 1px solid #8399ff;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSpinBox::up-button:disabled, QSpinBox::down-button:disabled,\n"
                            "QDoubleSpinBox::up-button:disabled, QDoubleSpinBox::down-button:disabled,\n"
                            "QDateTimeEdit::up-button:disabled, QDateTimeEdit::down-button:disabled\n"
                            "{\n"
                            "\tbackground-color: #404040;\n"
                            "\tcolor: #656565;\n"
                            "\tborder-color: #051a39;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSpinBox::up-button:pressed, QSpinBox::down-button:pressed,\n"
                            "QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button::pressed,\n"
                            "QDateTimeEdit::up-button:pressed, QDateTimeEdit::down-button::pressed\n"
                            "{\n"
                            "    background-color: #4969ff;\n"
                            "    border: 1px solid #4969ff;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSpinBox::down-arrow,\n"
                            "QDoubleSpinBox::down-arrow,\n"
                            "QDateTimeEdit::down-arrow\n"
                            "{\n"
                            "    image: url(://arrow-down.png);\n"
                            "    width: 7px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSpinBox::up-arrow,\n"
                            "QDoubleSpinBox::up-arrow,\n"
                            "QDateTimeEdit::up-arrow\n"
                            "{\n"
                            "    image: url(://arrow-up.png);\n"
                            "    width: 7px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "/*-----QLineEdit-----*/\n"
                            "QLineEdit\n"
                            "{\n"
                            "\tbackground-color: #525251;\n"
                            "\tcolor: #ffffff;\n"
                            "\tborder-width: 1px;\n"
                            "\tborder-radius: 3px;\n"
                            "\tborder-color: #051a39;\n"
                            "\tpadding: 2px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QLineEdit::disabled\n"
                            "{\n"
                            "\tbackground-color: #404040;\n"
                            "\tcolor: #656565;\n"
                            "\tborder-width: 1px;\n"
                            "\tborder-radius: 3px;\n"
                            "\tborder-color: #051a39;\n"
                            "\tpadding: 2px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "/*-----QTextEdit-----*/\n"
                            "QTextEdit\n"
                            "{\n"
                            "\t/* background-color: rgb(18, 18, 18); */\n"
                            "\tcolor: #cecece;\n"
                            "\tborder-color: #051a39;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTextEdit::disabled\n"
                            "{\n"
                            "\tbackground-color: #404040;\n"
                            "\tcolor: #656565;\n"
                            "\tborder-color: #051a39;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "/*-----QGroupBox-----*/\n"
                            "QGroupBox \n"
                            "{\n"
                            "    border: 1px solid;\n"
                            "    border-color: #607cff;\n"
                            "    margin-top: 22px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QGroupBox::title  \n"
                            "{\n"
                            "    background-color: #607cff;\n"
                            "    color: #ffffff;\n"
                            "    subcontrol-origin: margin;\n"
                            "    subcontrol-position: top left;\n"
                            "    padding: 5px;\n"
                            "\tborder-top-left-radius: 3px;\n"
                            "\tborder-top-right-radius: 3px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QGroupBox::title::disabled\n"
                            "{\n"
                            "\tbackground-color: #404040;\n"
                            "\tcolor: #656565;\n"
                            "    subcontrol-origin: margin;\n"
                            "    subcontrol-position: top left;\n"
                            "    padding: 5px;\n"
                            "\tborder-top-left-radius: 3px;\n"
                            "\tborder-top-right-radius: 3px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "/*-----QRadioButton-----*/\n"
                            "QRadioButton::indicator::unchecked\n"
                            "{ \n"
                            "\tborder: 2px inset gray; \n"
                            "\tborder-radius: 5px; \n"
                            "\tbackground-color:  #fff;\n"
                            "\twidth: 9px; \n"
                            "\theight: 9px; \n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QRadioButton::indicator::unchecked:hover\n"
                            "{ \n"
                            "\tborder: 2px solid #607cff; \n"
                            "\tborder-radius: 5px; \n"
                            "\tbackground-color:  #fff;\n"
                            "\twidth: 9px; \n"
                            "\theight: 9px; \n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QRadioButton::indicator::checked\n"
                            "{ \n"
                            "\tborder: 2px inset darkgray; \n"
                            "\tborder-radius: 5px; \n"
                            "\tbackground-color: #4969ff; \n"
                            "\twidth: 9px; \n"
                            "\theight: 9px; \n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QRadioButton::disabled\n"
                            "{\n"
                            "\tcolor: #656565;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QRadioButton::indicator:disabled\n"
                            "{\n"
                            "\tbackground-color: #656565;\n"
                            "\tcolor: #656565;\n"
                            "    border: 2px solid #656565;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "/*-----QTableView & QTableWidget-----*/\n"
                            "QTableView\n"
                            "{\n"
                            "    background-color: #242526;\n"
                            "    border: 1px solid #32414B;\n"
                            "    color: #f0f0f0;\n"
                            "    gridline-color: #8faaff;\n"
                            "    outline : 0;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTableView::disabled\n"
                            "{\n"
                            "    background-color: #242526;\n"
                            "    border: 1px solid #32414B;\n"
                            "    color: #656565;\n"
                            "    gridline-color: #656565;\n"
                            "    outline : 0;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTableView::item:hover \n"
                            "{\n"
                            "    background-color: #26264f;\n"
                            "    color: #f0f0f0;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTableView::item:selected \n"
                            "{\n"
                            "    background-color: #1a1b1c;\n"
                            "    border: 2px solid #4969ff;\n"
                            "    color: #F0F0F0;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTableView::item:selected:disabled\n"
                            "{\n"
                            "    background-color: #1a1b1c;\n"
                            "    border: 2px solid #525251;\n"
                            "    color: #656565;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTableCornerButton::section\n"
                            "{\n"
                            "    background-color: #505050;\n"
                            "    color: #fff;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QHeaderView::section\n"
                            "{\n"
                            "    background-color: #525251;\n"
                            "    color: #fff;\n"
                            "    text-align: left;\n"
                            "\tpadding: 4px;\n"
                            "\t\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QHeaderView::section:disabled\n"
                            "{\n"
                            "    background-color: #525251;\n"
                            "    color: #656565;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QHeaderView::section:checked\n"
                            "{\n"
                            "    color: #fff;\n"
                            "    background-color: #4969ff;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QHeaderView::section:checked:disabled\n"
                            "{\n"
                            "    color: #656565;\n"
                            "    background-color: #525251;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QHeaderView::section::vertical::first,\n"
                            "QHeaderView::section::vertical::only-one\n"
                            "{\n"
                            "    border-top: 1px solid #353635;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QHeaderView::section::vertical\n"
                            "{\n"
                            "    border-top: 1px solid #353635;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QHeaderView::section::horizontal::first,\n"
                            "QHeaderView::section::horizontal::only-one\n"
                            "{\n"
                            "    border-left: 1px solid #353635;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QHeaderView::section::horizontal\n"
                            "{\n"
                            "    border-left: 1px solid #353635;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "/*-----QTabWidget-----*/\n"
                            "QTabBar::tab\n"
                            "{\n"
                            "\tbackground-color: #262626;\n"
                            "\tcolor: #ffffff;\n"
                            "\tborder-style: solid;\n"
                            "\tborder-width: 1px;\n"
                            "\tborder-top-left-radius: 3px;\n"
                            "\tborder-top-right-radius: 3px;\n"
                            "\tborder-color: #051a39;\n"
                            "\tpadding: 5px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabBar::tab:disabled\n"
                            "{\n"
                            "\tbackground-color: #656565;\n"
                            "\tcolor: #656565;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabWidget::pane \n"
                            "{\n"
                            "\tbackground-color: #262626;\n"
                            "\tcolor: #ffffff;\n"
                            "    border: 1px solid;\n"
                            "    border-color: #607cff;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabBar::tab:selected\n"
                            "{\n"
                            "    background-color: #607cff;\n"
                            "\tcolor: #ffffff;\n"
                            "\tborder-style: solid;\n"
                            "\tborder-width: 1px;\n"
                            "\tborder-top-left-radius: 3px;\n"
                            "\tborder-top-right-radius: 3px;\n"
                            "\tborder-color: #051a39;\n"
                            "\tpadding: 5px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabBar::tab:selected:disabled\n"
                            "{\n"
                            "\tbackground-color: #404040;\n"
                            "\tcolor: #656565;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabBar::tab:!selected \n"
                            "{\n"
                            "    background-color: #262626;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabBar::tab:!selected:hover \n"
                            "{\n"
                            "    background-color: #8399ff;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabBar::tab:top:!selected \n"
                            "{\n"
                            "    margin-top: 3px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabBar::tab:bottom:!selected \n"
                            "{\n"
                            "    margin-bottom: 3px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabBar::tab:top, QTabBar::tab:bottom \n"
                            "{\n"
                            "    min-width: 8ex;\n"
                            "    margin-right: -1px;\n"
                            "    padding: 5px 10px 5px 10px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabBar::tab:top:selected \n"
                            "{\n"
                            "    border-bottom-color: none;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabBar::tab:bottom:selected \n"
                            "{\n"
                            "    border-top-color: none;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
                            "QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one \n"
                            "{\n"
                            "    margin-right: 0;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabBar::tab:left:!selected \n"
                            "{\n"
                            "    margin-right: 3px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabBar::tab:right:!selected\n"
                            "{\n"
                            "    margin-left: 3px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabBar::tab:left, QTabBar::tab:right \n"
                            "{\n"
                            "    min-height: 8ex;\n"
                            "    margin-bottom: -1px;\n"
                            "    padding: 10px 5px 10px 5px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabBar::tab:left:selected \n"
                            "{\n"
                            "    border-left-color: none;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabBar::tab:right:selected \n"
                            "{\n"
                            "    border-right-color: none;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
                            "QTabBar::tab:left:only-one, QTabBar::tab:right:only-one \n"
                            "{\n"
                            "    margin-bottom: 0;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "/*-----QSlider-----*/\n"
                            "QSlider::groove:horizontal \n"
                            "{\n"
                            "\tbackground-color: transparent;\n"
                            "\theight: 5px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSlider::sub-page:horizontal \n"
                            "{\n"
                            "\tbackground-color: #607cff;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSlider::add-page:horizontal \n"
                            "{\n"
                            "\tbackground-color: #666765;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSlider::handle:horizontal \n"
                            "{\n"
                            "\tbackground-color: #607cff;\n"
                            "\twidth: 14px;\n"
                            "\tmargin-top: -6px;\n"
                            "\tmargin-bottom: -6px;\n"
                            "\tborder-radius: 3px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSlider::handle:horizontal:hover \n"
                            "{\n"
                            "\tbackground-color: #607cff;\n"
                            "\tborder-radius: 3px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSlider::sub-page:horizontal:disabled \n"
                            "{\n"
                            "\tbackground-color: #bbb;\n"
                            "\tborder-color: #999;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSlider::add-page:horizontal:disabled \n"
                            "{\n"
                            "\tbackground-color: #eee;\n"
                            "\tborder-color: #999;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSlider::handle:horizontal:disabled \n"
                            "{\n"
                            "\tbackground-color: #eee;\n"
                            "\tborder: 1px solid #aaa;\n"
                            "\tborder-radius: 3px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSlider::groove:vertical \n"
                            "{\n"
                            "\tbackground-color: transparent;\n"
                            "\twidth: 5px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSlider::sub-page:vertical \n"
                            "{\n"
                            "\tbackground-color: #607cff;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSlider::add-page:vertical \n"
                            "{\n"
                            "\tbackground-color: #666765;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSlider::handle:vertical \n"
                            "{\n"
                            "\tbackground-color: #607cff;\n"
                            "\theight: 14px;\n"
                            "\tmargin-left: -6px;\n"
                            "\tmargin-right: -6px;\n"
                            "\tborder-radius: 3px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSlider::handle:vertical:hover \n"
                            "{\n"
                            "\tbackground-color: #607cff;\n"
                            "\tborder-radius: 3px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSlider::sub-page:vertical:disabled \n"
                            "{\n"
                            "\tbackground-color: #bbb;\n"
                            "\tborder-color: #999;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSlider::add-page:vertical:disabled \n"
                            "{\n"
                            "\tbackground-color: #eee;\n"
                            "\tborder-color: #999;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QSlider::handle:vertical:disabled \n"
                            "{\n"
                            "\tbackground-color: #eee;\n"
                            "\tborder: 1px solid #aaa;\n"
                            "\tborder-radius: 3px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "/*-----QDial-----*/\n"
                            "QDial\n"
                            "{\n"
                            "\tbackground-color: #607cff;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QDial::disabled\n"
                            "{\n"
                            "\tbackground-color: #404040;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "/*-----QScrollBar-----*/\n"
                            "QScrollBar:horizontal\n"
                            "{\n"
                            "    border: 1px solid #222222;\n"
                            "    background-color: #3d3d3d;\n"
                            "    height: 13px;\n"
                            "    margin: 0px 16px 0 16px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QScrollBar::handle:horizontal\n"
                            "{\n"
                            "    background: #607cff;\n"
                            "    min-height: 20px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QScrollBar::add-line:horizontal\n"
                            "{\n"
                            "    border: 1px solid #1b1b19;\n"
                            "    background-color: #607cff;\n"
                            "    width: 14px;\n"
                            "    subcontrol-position: right;\n"
                            "    subcontrol-origin: margin;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QScrollBar::sub-line:horizontal\n"
                            "{\n"
                            "    border: 1px solid #1b1b19;\n"
                            "    background-color: #607cff;\n"
                            "    width: 14px;\n"
                            "    subcontrol-position: left;\n"
                            "    subcontrol-origin: margin;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QScrollBar::right-arrow:horizontal\n"
                            "{\n"
                            "    image: url(://arrow-right.png);\n"
                            "    width: 6px;\n"
                            "    height: 6px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QScrollBar::left-arrow:horizontal\n"
                            "{\n"
                            "    image: url(://arrow-left.png);\n"
                            "    width: 6px;\n"
                            "    height: 6px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
                            "{\n"
                            "    background: none;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QScrollBar:vertical\n"
                            "{\n"
                            "    background-color: #3d3d3d;\n"
                            "    width: 13px;\n"
                            "    margin: 16px 0 16px 0;\n"
                            "    border: 1px solid #222222;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QScrollBar::handle:vertical\n"
                            "{\n"
                            "    background-color: #607cff;\n"
                            "    min-height: 20px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QScrollBar::add-line:vertical\n"
                            "{\n"
                            "    border: 1px solid #1b1b19;\n"
                            "    background-color: #607cff;\n"
                            "    height: 14px;\n"
                            "    subcontrol-position: bottom;\n"
                            "    subcontrol-origin: margin;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QScrollBar::sub-line:vertical\n"
                            "{\n"
                            "    border: 1px solid #1b1b19;\n"
                            "    background-color: #607cff;\n"
                            "    height: 14px;\n"
                            "    subcontrol-position: top;\n"
                            "    subcontrol-origin: margin;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QScrollBar::up-arrow:vertical\n"
                            "{\n"
                            "    image: url(://arrow-up.png);\n"
                            "    width: 6px;\n"
                            "    height: 6px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QScrollBar::down-arrow:vertical\n"
                            "{\n"
                            "    image: url(://arrow-down.png);\n"
                            "    width: 6px;\n"
                            "    height: 6px;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "\n"
                            "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
                            "{\n"
                            "    background: none;\n"
                            "\n"
                            "}\n"
                            "\n"
                            "/*-----QProgressBar-----*/\n"
                            "QProgressBar\n"
                            "{\n"
                            "    border: 1px solid #222222;\n"
                            "    background-color: #3d3d3d;\n"
                            "    text-align: center;\n"
                            "    color: #ffffff;\n"
                            "    font-size: 12px;\n"
                            "    /* font-weight: bold; */\n"
                            "    padding: 1px;\n"
                            "    border-radius: 3px;\n"
                            "}\n"
                            "QProgressBar::chunk\n"
                            "{\n"
                            "    background-color: #607cff;\n"
                            "}";

inline QString cssDevision = "/*Copyright (c) DevSec Studio. All rights reserved.\n"
                          "\n"
                          "MIT License\n"
                          "\n"
                          "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
                          "of this software and associated documentation files (the \"Software\"), to deal\n"
                          "in the Software without restriction, including without limitation the rights\n"
                          "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
                          "copies of the Software, and to permit persons to whom the Software is\n"
                          "furnished to do so, subject to the following conditions:\n"
                          "\n"
                          "The above copyright notice and this permission notice shall be included in all\n"
                          "copies or substantial portions of the Software.\n"
                          "\n"
                          "THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
                          "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
                          "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
                          "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
                          "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
                          "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
                          "*/\n"
                          "\n"
                          "/*-----QWidget-----*/\n"
                          "QWidget\n"
                          "{\n"
                          "\tbackground-color: #00111d;\n"
                          "\tcolor: #000000;\n"
                          "\tborder-color: #000000;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "/*-----QLabel-----*/\n"
                          "QLabel\n"
                          "{\n"
                          "\tbackground-color: #00111d;\n"
                          "\tcolor: #717e87;\n"
                          "\tborder-color: #000000;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "/*-----QPushButton-----*/\n"
                          "QPushButton\n"
                          "{\n"
                          "\tbackground-color: #3de6af;\n"
                          "\tcolor: #000000;\n"
                          "\tborder-style: solid;\n"
                          "\tborder-color: #000000;\n"
                          "\tfont-weight : bold;\n"
                          "\tpadding: 13px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QPushButton::hover\n"
                          "{\n"
                          "\tbackground-color: #3dffaf;\n"
                          "\tcolor: #000000;\n"
                          "\tborder-style: solid;\n"
                          "\tborder-color: #000000;\n"
                          "\tfont-weight : bold;\n"
                          "\tpadding: 13px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QPushButton::pressed\n"
                          "{\n"
                          "\tbackground-color: #3dc8af;\n"
                          "\tcolor: #000000;\n"
                          "\tborder-style: solid;\n"
                          "\tborder-color: #000000;\n"
                          "\tfont-weight : bold;\n"
                          "\tpadding: 13px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "/*-----QToolButton-----*/\n"
                          "QToolButton\n"
                          "{\n"
                          "\tbackground-color: #00111d;\n"
                          "\tcolor: #000000;\n"
                          "\tborder-style: solid;\n"
                          "\tborder-color: #000000;\n"
                          "\tpadding: 5px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QToolButton::hover\n"
                          "{\n"
                          "\tbackground-color: #00111d;\n"
                          "\tcolor: #000000;\n"
                          "\tborder-style: solid;\n"
                          "\tborder-width: 1px;\n"
                          "\tborder-color: #01dcff;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QToolButton::pressed\n"
                          "{\n"
                          "\tbackground-color: #01dcff;\n"
                          "\tcolor: #000000;\n"
                          "\tborder-style: solid;\n"
                          "\tborder-width: 1px;\n"
                          "\tborder-color: #01dcff;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "/*-----QLineEdit-----*/\n"
                          "QLineEdit\n"
                          "{\n"
                          "\tbackground-color: #082336;\n"
                          "\tcolor: #3e93ff;\n"
                          "\tborder-style: solid;\n"
                          "\tborder-width: 2px;\n"
                          "\tborder-color: #1e4b6d;\n"
                          "\tpadding: 10px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QLineEdit::hover\n"
                          "{\n"
                          "\tbackground-color: #082336;\n"
                          "\tcolor: #3e93ca;\n"
                          "\tborder-style: solid;\n"
                          "\tborder-width: 2px;\n"
                          "\tborder-color: #01dcff;\n"
                          "\tpadding: 10px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QLineEdit::focus\n"
                          "{\n"
                          "\t\n"
                          "\tcolor: #3e93ca;\n"
                          "\tborder-style: solid;\n"
                          "\tborder-width: 2px;\n"
                          "\tborder-color: #01dcff;\n"
                          "\tpadding: 10px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "/*-----QCheckBox-----*/\n"
                          "QCheckBox\n"
                          "{\n"
                          "\tbackground-color: transparent;\n"
                          "\tcolor: #717e87;\n"
                          "\tborder-color: #000000;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QCheckBox::indicator\n"
                          "{\n"
                          "    color: #b1b1b1;\n"
                          "    background-color: #00111d;\n"
                          "    border: 1px solid #2aaaa8;\n"
                          "    width: 12px;\n"
                          "    height: 12px;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QCheckBox::indicator:checked\n"
                          "{\n"
                          "    image:url(\"./ressources/check.png\"); /*To replace*/\n"
                          "\tbackground-color: #1f2b2b;\n"
                          "    border: 1px solid #2aaaa8;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QCheckBox::indicator:unchecked:hover\n"
                          "{\n"
                          "    border: 1px solid #2aaaa8;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QCheckBox::disabled\n"
                          "{\n"
                          "\tcolor: #656565;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "QCheckBox::indicator:disabled\n"
                          "{\n"
                          "\tbackground-color: #656565;\n"
                          "\tcolor: #656565;\n"
                          "    border: 1px solid #656565;\n"
                          "\n"
                          "}\n"
                          "\n"
                          "\n"
                          "";

inline QString svgCancelCode =R"(<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="green" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" class="feather feather-log-in"><path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"></path><polyline points="10 17 15 12 10 7"></polyline><line x1="15" y1="12" x2="3" y2="12"></line></svg>)";