#pragma once 

#include <QString>
#include "./mnlibrary/mndb_types.h"
     const
float db_version =1;
const QString db_options_design_json="{"
"	\"database_name\": \"db_options_design\","
"	\"tables\": ["
"		{"
"			\"table_name\": \"databases\","
"			\"fields\": ["
"				{"
"					\"field_name\": \"db_name\","
"					\"field_type\": \"VARCHAR\","
"					\"field_length\": 255,"
"					\"is_unique\": true,"
"					\"is_not_null\": true,"
"					\"is_indexed\": true,"
"					\"default_value\": \"\","
"					\"description\": \"path or name if server\","
"					\"is_required\": true,"
"					\"is_visible\": true,"
"					\"is_read_only\": false,"
"					\"display_width\": 20,"
"					\"display_label\": \"DATABASE\","
"					\"is_calculated\": false,"
"					\"ind\": 9"
"				},"
"				{"
"					\"field_name\": \"is_server\","
"					\"field_type\": \"BOOL\","
"					\"field_length\": 0,"
"					\"is_unique\": false,"
"					\"is_not_null\": false,"
"					\"is_indexed\": false,"
"					\"default_value\": \"\","
"					\"description\": \"\","
"					\"is_required\": false,"
"					\"is_visible\": true,"
"					\"is_read_only\": false,"
"					\"display_width\": 0,"
"					\"display_label\": \"\","
"					\"is_calculated\": false,"
"					\"ind\": 10"
"				},"
"				{"
"					\"field_name\": \"user_name\","
"					\"field_type\": \"VARCHAR\","
"					\"field_length\": 255,"
"					\"is_unique\": false,"
"					\"is_not_null\": false,"
"					\"is_indexed\": false,"
"					\"default_value\": \"\","
"					\"description\": \"\","
"					\"is_required\": false,"
"					\"is_visible\": true,"
"					\"is_read_only\": false,"
"					\"display_width\": 20,"
"					\"display_label\": \"UTILISATEUR\","
"					\"is_calculated\": false,"
"					\"ind\": 11"
"				},"
"				{"
"					\"field_name\": \"password\","
"					\"field_type\": \"VARCHAR\","
"					\"field_length\": 255,"
"					\"is_unique\": false,"
"					\"is_not_null\": false,"
"					\"is_indexed\": false,"
"					\"default_value\": \"\","
"					\"description\": \"\","
"					\"is_required\": false,"
"					\"is_visible\": true,"
"					\"is_read_only\": false,"
"					\"display_width\": 12,"
"					\"display_label\": \"MOT DE PASS\","
"					\"is_calculated\": false,"
"					\"ind\": 12"
"				},"
"				{"
"					\"field_name\": \"port\","
"					\"field_type\": \"INTEGER\","
"					\"field_length\": 0,"
"					\"is_unique\": false,"
"					\"is_not_null\": false,"
"					\"is_indexed\": false,"
"					\"default_value\": \"\","
"					\"description\": \"\","
"					\"is_required\": false,"
"					\"is_visible\": true,"
"					\"is_read_only\": false,"
"					\"display_width\": 0,"
"					\"display_label\": \"PORTE\","
"					\"is_calculated\": false,"
"					\"ind\": 13"
"				},"
"				{"
"					\"field_name\": \"is_active\","
"					\"field_type\": \"BOOL\","
"					\"field_length\": 0,"
"					\"is_unique\": false,"
"					\"is_not_null\": false,"
"					\"is_indexed\": false,"
"					\"default_value\": \"\","
"					\"description\": \"\","
"					\"is_required\": false,"
"					\"is_visible\": true,"
"					\"is_read_only\": false,"
"					\"display_width\": 0,"
"					\"display_label\": \"ACTIVE\","
"					\"is_calculated\": false,"
"					\"ind\": 14"
"				}],"
"			\"default_data\": \"\","
"			\"description\": \"\","
"			\"insert_sql\": \"    INSERT INTO \"databases\"(\"db_name\",\"is_server\",\"user_name\",\"password\",\"port\",\"is_active\")\n    VALUES(:db_name,:is_server,:user_name,:password,:port,:is_active);\","
"			\"insert_params_count\": 6,"
"			\"is_view\": false,"
"			\"create_sql\": \"\""
"		}],"
"	\"version\": 1,"
"	\"description\": \"\","
"	\"db_path\": \"\""
"}"
;


    //----------------------------databases---------------------------------

const QString databases_table_name="databases";
const QString sql_databases_tbl_create= "  CREATE TABLE \"databases\" ("
"     \"id\" INTEGER PRIMARY KEY {if Sqlite} AUTOINCREMENT {else} AUTO_INCREMENT {endif},"
"     \"db_name\" VARCHAR(255)  UNIQUE  NOT NULL ,"
"     \"is_server\" BOOL,"
"     \"user_name\" VARCHAR(255) ,"
"     \"password\" VARCHAR(255) ,"
"     \"port\" INTEGER,"
"     \"is_active\" BOOL);"
 ;

const QString databases_db_name="db_name";
const QString databases_is_server="is_server";
const QString databases_user_name="user_name";
const QString databases_password="password";
const QString databases_port="port";
const QString databases_is_active="is_active";
const QString sql_databases_insert="    INSERT INTO \"databases\"(\"db_name\",\"is_server\",\"user_name\",\"password\",\"port\",\"is_active\")"
"    VALUES(:db_name,:is_server,:user_name,:password,:port,:is_active);"
;

 MnDatabaseDef db_options_design_def(db_options_design_json);
